# Generated by Django 3.1.7 on 2021-04-03 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tafsili',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.IntegerField()),
                ('kol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moins', to='api.kol')),
            ],
        ),
        migrations.CreateModel(
            name='Artykl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bed', models.FloatField()),
                ('bes', models.FloatField()),
                ('note', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('kol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kols', to='api.kol')),
                ('moin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moins', to='api.moin')),
                ('sanad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artykls', to='api.sanad')),
                ('taf1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taf1s', to='api.tafsili')),
                ('taf2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taf2s', to='api.tafsili')),
                ('taf3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taf3s', to='api.tafsili')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
