# Generated by Django 3.1.7 on 2021-04-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210403_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artykl',
            options={'verbose_name_plural': 'آرتیکل های حسابداری'},
        ),
        migrations.AlterModelOptions(
            name='moin',
            options={'verbose_name_plural': 'حسابهای معین'},
        ),
        migrations.AlterModelOptions(
            name='sanad',
            options={'verbose_name_plural': 'اسناد حسابداری'},
        ),
        migrations.AlterModelOptions(
            name='tafsili',
            options={'verbose_name_plural': 'حسابهای تفصیلی'},
        ),
    ]
