# Generated by Django 3.1.7 on 2021-04-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210403_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykl',
            name='bed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='artykl',
            name='bes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='artykl',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artykl',
            name='taf1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taf1s', to='api.tafsili'),
        ),
        migrations.AlterField(
            model_name='artykl',
            name='taf2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taf2s', to='api.tafsili'),
        ),
        migrations.AlterField(
            model_name='artykl',
            name='taf3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taf3s', to='api.tafsili'),
        ),
    ]
