# Generated by Django 3.1.7 on 2021-04-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categgory',
            new_name='Category',
        ),
    ]
